title: Writing nonsense
description: Nasi goreng very nice

url: https://changhc.me/blog
paginate_path: "page:num/"
permalink: :title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

social:
  github: changhc
  email: hello@changhc.me
  linkedin: ~hc

google_analytics: "UA-76356561-1"
